### ISSUE TITLE
XCode compiler / linker errors

### ISSUE THREAD

**Issue by chrisError** [adobe/unity-acpcore#25]
I currently can't compile our Unity project from XCode. I am getting the following Linker errors (along with roughly 20 others all the same)
```
Undefined symbols for architecture arm64:
  "_sqlite3_bind_int", referenced from:
      AdobeMarketingMobile::Database::SqlBindStatement(sqlite3_stmt*, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::shared_ptr<AdobeMarketingMobile::Variant>, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::shared_ptr<AdobeMarketingMobile::Variant> > > > const&) in libACPCore_iOS.a(NativeDatabaseService.o)

```

I have tried adding libsqlite3 in "Link Binary With Libraries" but that does not seem to solve it for me.

**Comment by sbenedicadb** [comment]
Hey @chrisError -

Are you able to compile your project for device?  Or is the error affecting both simulator and device?  Thanks.

-steveb

**Comment by chrisError** [comment]
Unity apps can't run in Simulator(alas!) so this is a device build (it crashes out in the linking phase)

**Comment by sbenedicadb** [comment]
Gotcha.  Are all the other errors naming sqlite3 as well?

**Comment by chrisError** [comment]
@sbenedicadb I think I have solved it. I needed to add libsql3 and libz as linked binaries to the UnityFramework. thanks for the speedy responses none the less!
