### ISSUE TITLE
Feature request: unitypackages

### ISSUE THREAD

**Issue by ralphtherapper** [adobe/unity-acpcore#30]
As these Adobe plugins are unity plugins it would be fitting that these plugins would be included to unity through unity package manager.

Other than that thanks for well sorted repo and docs.

**Comment by spoorthipujariadobe** [comment]
@ralphtherapper since the Adobe Unity AEP SDKs are open source, we do not plan on releasing them using Unity package manager.

Thanks,
Spoorthi

**Comment by ralphtherapper** [comment]
Appreciate the reply. Yet I want to point out that this does not change status of the module to be anything else than open source. 

Thanks,
- Sami
